### ISSUE TITLE
"Login" testcase has to work on a fresh environment

### ISSUE THREAD

**Issue by extsoft** [extsoft/dp-151#26]
If I run `oct/tests/web/login.py` in a new environment, it will fail. Please make it working on a fresh environment also.

Use API logic to create a user. See #29 #28

**Comment by extsoft** [comment]
@AlekseyDidilov this task is not implemented.

**Comment by AlekseyDidilov** [comment]
> @AlekseyDidilov this task is not implemented.

@extsoft I've missed part of this task, now i added new PR, where it was implemented.
